#!/usr/local/bin/ruby -Ku
# -*- coding: utf-8 -*-

$LOAD_PATH << ".." if $0 == __FILE__

require "pp"

require "parsedate"
require "md5"
require "find"

require "config"

require "db_client"
require "recfile"
require "tool"
require "simulator"
require "input"
require "graph"

require "signal_observer"
require "with_sound"

require "load_all"

about = []
about << "About your application's environment"
about << "TETRiS Library version  #{CONFIG[:version]}"
about << "Ruby version            #{RUBY_VERSION}"
about << "Ruby/SDL version        #{SDL::VERSION} 拡張機能(#{UI::Sdl.spec.join(",")})"
about << "mplayer version         #{`mplayer --help`.to_a.first.strip}"
about << "mencoder version        #{`mencoder 2>&1`.to_a.first.strip}"
about << "mogrify version         #{`mogrify -version`.to_a.first.strip}"
about << "gnuplot version         #{`which gnuplot`}"
puts about.join("\n")
