require File.expand_path(File.join(File.dirname(__FILE__), "play"))
require File.expand_path(File.join(File.dirname(__FILE__), "score"))
require File.expand_path(File.join(File.dirname(__FILE__), "input"))
require File.expand_path(File.join(File.dirname(__FILE__), "pattern"))
require File.expand_path(File.join(File.dirname(__FILE__), "sound_controller"))
