#!/usr/local/bin/ruby
# $Id$

$: << '..'
require 'simulator'

library = [
  {
    :title => "1. 前回:�譒�論",
    :author => "ZON",
    :date => "2000-01-29",
    :url => "http://homepage3.nifty.com/tgm/bbslog0001.html",
    :difficulty => 5,
    :comment => "�笒�一手が雒�しい",
    :ctrl => SimCtrl.new,
    :pattern => "p",
    :field => <<-EOT,
    ..........
    .....o....
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    EOT
    :input => <<-EOT
    r| d *
    EOT
  },
]

if $0 == __FILE__
  Simulator.start(library.reverse.find{|e|!e[:input].nil?}, 60)


#   Simulator::Movie.sample_to_mpeg(library[0],"hoge.mpg", __FILE__)
#   exit

#   Simulator.start_sample(library[0],30)
#   p library[0][:ctrl]
#   Simulator.start_sample(library[0],30)
#   p library[0][:ctrl]


  exit
  library.each{|e| break if Simulator.start_sample(e, 60) == :break}
  Simulator.start_sample(library.reverse.find{|e|!e[:input].nil?}, 60)
end

library
